export const DIFFICULTY = {
  CADET: {
    id: 'CADET',
    label: 'Cadet',
    wpm: 5,
    showReferenceCard: true,
    autoDecodeDelay: 3000,
    timingTolerance: 0.25,
    staticLevel: 0.1,
    description: 'Full reference card, auto-decoded text shown with delay.',
  },
  JUNIOR: {
    id: 'JUNIOR',
    label: 'Junior Operator',
    wpm: 8,
    showReferenceCard: 'hover',
    autoDecodeDelay: 0,
    timingTolerance: 0.20,
    staticLevel: 0.2,
    description: 'Reference card on hover, partial auto-decode.',
  },
  OPERATOR: {
    id: 'OPERATOR',
    label: 'Operator',
    wpm: 12,
    showReferenceCard: false,
    autoDecodeDelay: 0,
    timingTolerance: 0.15,
    staticLevel: 0.3,
    description: 'No reference card. Decoded text shows only what you type.',
  },
  SENIOR: {
    id: 'SENIOR',
    label: 'Senior Operator',
    wpm: 15,
    showReferenceCard: false,
    autoDecodeDelay: 0,
    timingTolerance: 0.10,
    staticLevel: 0.35,
    description: 'Q-codes and abbreviations required.',
  },
  MARCONI: {
    id: 'MARCONI',
    label: 'Marconi Man',
    wpm: 18,
    showReferenceCard: false,
    autoDecodeDelay: 0,
    timingTolerance: 0.05,
    staticLevel: 0.45,
    description: 'Prosigns, commercial traffic, overlapping signals.',
  },
};
